# Generated by Django 4.2 on 2025-01-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='project',
            field=models.ManyToManyField(to='portfolio.project'),
        ),
    ]
