# Generated by Django 4.2 on 2025-01-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_rename_icon_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='feedback',
            field=models.TextField(),
        ),
    ]
